### ISSUE TITLE
Scroll til riktig section i om oss siden, når den laster inn

### ISSUE THREAD

**Issue by emberal** [Project-insert-name/root-website#101]
Dersom # anchor er satt i url og man laster inn siden, så vil ikke vinduet scrolle ned

Virker ikke i det hele tatt på Firefox, men virker av og til på Chrome baserte nettlesere. Mulig det har noe med at data lastes inn å gjøre, og section er ikke tilgjengelig med en gang.

Mulig løsning: https://ericdcobb.medium.com/scrolling-to-an-anchor-in-react-when-your-elements-are-rendered-asynchronously-8c64f77b5f34

**Comment by 594760** [comment]
Det funker på deployet versjon av #102 hos meg

**Comment by emberal** [comment]
Hmm. Lurer på om det er et Firefox problem. Testet nettopp i chrome og det funker fint. Men ikke i Firefox på prod eller den branchen

**Comment by 594760** [comment]
Får du gjenskapet problemet? jeg får ikke det til.

**Comment by emberal** [comment]
Ser ut til at det virker som det skal nå ja...
Mulig det var en bug i en dependency som har blitt oppdatert
