### ISSUE TITLE
Bytte fra markdown til rich text editor

### ISSUE THREAD

**Issue by 594760** [Project-insert-name/root-website#103]
Etter å ha brukt markdown litt nå syns jeg det virker beder å bruke en rich text editor. Den er mye enklere å bruke istede for markdown når man ikke er veldig god i markdown.

**Comment by emberal** [comment]
Ja tror det kan være lurt, vil nok gjøre det lettere for andre som ikke er vant med Markdown også.

Tror det er denne typen https://www.sanity.io/docs/block-type
