### ISSUE TITLE
Mulighet til å subscribe til arrangement

### ISSUE THREAD

**Issue by emberal** [Project-insert-name/root-website#105]
Nå er det mulig å laste ned en .ics fil å legge den til i kalender, men dersom arrangementet endres vil det ikke endres i kalenderen. Dersom vi hoster .ics filen på serveren i stedet så kan man subscribe på den med kalenderen. Slik at når filen endres, så oppdateres innholdet i kalenderen også.

Krever
- Mulighet for å lagre .ics filer lokalt på server
- Endre innholdet i dem når et arrangement endres
- Et endepunkt for å hente dem ut

**Comment by emberal** [comment]
Endepunkt kunne e.eks. vært https://www.rootlinjeforening.no/arrangement/bedriftspresentasjon-med-tv2-v2024.ics
Hvor slug blir brukt for å hente ut info om arrangement fra Sanity, også lage og returnere .ics filen.

Kan bruke en Next.js route https://nextjs.org/docs/app/building-your-application/routing/route-handlers

**Comment by 594760** [comment]
Error ved deploy:
```
10:52:40.100 | Failed to compile.
10:52:40.100 |  
10:52:40.100 | app/(root)/api/arrangement/[slug]/route.ts
10:52:40.100 | Type error: Route "app/(root)/api/arrangement/[slug]/route.ts" has an invalid "GET" export:
10:52:40.101 | Type "Params" is not a valid type for the function's first argument.
10:52:40.101 | Expected "NextRequest \| Request", got "Params".
10:52:40.101
```
[https://root-website-git-105-ics-subscribe-pin-root-webside.vercel.app?_vercel_share=0RHarbDM0cKd8VDo0BlmIZXdXNOovrPt](https://root-website-git-105-ics-subscribe-pin-root-webside.vercel.app?_vercel_share=0RHarbDM0cKd8VDo0BlmIZXdXNOovrPt)
