### ISSUE TITLE
Bytte til ny logo, og erstatt stilen slik at det passer med logoen.

### ISSUE THREAD

**Issue by emberal** [Project-insert-name/root-website#115]
Vet ikke helt når den nye logoen skal tas i bruk, men går an å lage en branch på det for å teste med design

**Comment by 594760** [comment]
Tror ikke logen er hundre prosent klar men kan legge inn det vi har foreløpig på en branch. Det er også tenkt å laget et favicon.

**Comment by 594760** [comment]
Har lagt inn de logoene vi har nå det kommer til å være noe endriger f.eks favicon vil bli endret. De ligger under public/new-logo
