### ISSUE TITLE
Deployement

### ISSUE THREAD

**Issue by emberal** [Project-insert-name/root-website#20]
Vercel?

**Comment by 594760** [comment]
Hva må vi gjøre før vi kan gå live?
tenker selv at vi bør gjøre ferdig #29 #83 og kansje #81, #44

**Comment by emberal** [comment]
Midlertidig deployet til Vercel. Flyttes til FriByte senere

**Comment by simsine** [comment]
> Midlertidig deployet til Vercel. Flyttes til FriByte senere

Angående dette så er Fribyte serveren allerede oppe med applikasjonen kjørende, det trengs fortsatt å blant annet sette opp kontinuerlig deployment via github actions.
Å produksjonsette fribyte deployment vil ikke skje før jeg er ferdig med dette og etter jeg eller Nick forhåpentligvis har mer direkte kontroll over domenet.
Arbeidet vil skje på deploy branchen.

**Comment by 594760** [comment]
> > Midlertidig deployet til Vercel. Flyttes til FriByte senere
> 
> Angående dette så er Fribyte serveren allerede oppe med applikasjonen kjørende, det trengs fortsatt å blant annet sette opp kontinuerlig deployment via github actions. Å produksjonsette fribyte deployment vil ikke skje før jeg er ferdig med dette og etter jeg eller Nick forhåpentligvis har mer direkte kontroll over domenet. Arbeidet vil skje på deploy branchen.

Opprettet en ny issue på dett #98.
Finner ingen deploy branch? Er bare litt nysgjerrig.
