### ISSUE TITLE
Metadata for hver route

### ISSUE THREAD

**Issue by emberal** [Project-insert-name/root-website#27]
https://nextjs.org/docs/app/building-your-application/optimizing/metadata

Tittel og en beskrivelse for siden

**Comment by 594760** [comment]
Bump er det noe nytt her? @emberal

**Comment by emberal** [comment]
Er lagt til noe på alle sidene, noen har statisk mens noen har litt dynamisk som arrangement. Kan sikkert gjøre mer, som å legge til tags. Men tror det er greit i første omgang
