### ISSUE TITLE
Definere Stillingsannonse skjema

### ISSUE THREAD

**Issue by 594760** [Project-insert-name/root-website#50]
-Bedrifts navn*
-Stilling*
-Antall stillinger 
-Søknadsfrist
-Beskrivelse
-Link søknad*
-Bilde muligheter (Logo bedrift)
\* må være med for å opprette stillingsannonse

**Comment by emberal** [comment]
Denne er i utgangspunktet ferdig. Dersom det er noe som mangler, kan den åpnes igjen med en kommentar
