### ISSUE TITLE
Fiks: studio route, Invalid hook call

### ISSUE THREAD

**Issue by simsine** [Project-insert-name/root-website#59]
Når StudioPage komponenten blir rendret spytter React ut en vegg av denne erroren:
![image](https://github.com/Project-insert-name/root-website/assets/89988615/ea7012bb-e8c7-444a-823e-b7e84fec3e22)
Ut ifra [denne issuen](https://www.sanity.io/answers/troubleshooting--invalid-hook-call--warnings-in-sanity-studio-console) ser det ut som at det kan være et problem med styled components.

**Comment by emberal** [comment]
Ut i fra [denne](https://www.sanity.io/answers/troubleshooting--invalid-hook-call--warnings-in-sanity-studio-console) threaden ser det ut til å være styled components pakken som Sanity bruker ja.

Det kan være at feilen forsvinner hvis vi oppdaterer alle pakkene. Kan teste litt senere
