### ISSUE TITLE
Forklaring på fargene på arrangementer

### ISSUE THREAD

**Issue by 594760** [Project-insert-name/root-website#80]
Forklaring på fargene på arrangementer. Lage en forklaring på hva de forskjelige fargen betyr.
![Screenshot from 2024-01-13 00-26-58](https://github.com/Project-insert-name/root-website/assets/89256648/e0274d5b-3b28-4afa-abc7-ea580ef551cd)

**Comment by 594760** [comment]
Forslag til hvordan det kan løses
Vise en kort stripe av fargen så et forklarened navn hva det er. Hoverefekt på farge viser hva det er.

**Comment by 594760** [comment]
@emberal  @simsine  
Dette er noe jeg syns haster. Enig?
Noen av dere som vil fikse det?

**Comment by 594760** [comment]
Kan kansje kobineres med #68 Slik at der vi kan filterer trenger vi ikke å forklare hva de er for filtreringen forklarer nok. Men er ikke sikkert vi tillater filtrering på framisden.

**Comment by emberal** [comment]
Vet ikke helt hva du mener, men er jo mulig å bare vise det under tittelen

![image](https://github.com/Project-insert-name/root-website/assets/89257606/85a7d7be-96c1-4a0a-910d-da9109d66c90)

**Comment by 594760** [comment]
Kan gjøre det å men børr vertfall forklare eller skrive det som du viser

**Comment by simsine** [comment]
Surely bare legg til title atribute på baren med event type

**Comment by emberal** [comment]
> Surely bare legg til title atribute på baren med event type

Det er gjort, men det vil ikke vises på mobil

**Comment by simsine** [comment]
Ah sant nok
